apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-project:v1
          ports:
            - containerPort: 9098
          volumeMounts:
            - name: config-volume
              mountPath: /home/config
      volumes:
        - name: config-volume
          configMap:
            name: application-config